import { Agent, LocationId } from '../types'
import { nanoid } from 'nanoid'

function createAgent(partial: {
  bio: Agent['bio']
  archetype: string
  traits: Agent['traits']
  location?: LocationId
}): Agent {
  return {
    id: nanoid(),
    bio: partial.bio,
    archetype: partial.archetype,
    traits: partial.traits,
    needs: {
      socialNeed: 70 + Math.random() * 20,
      validationNeed: 60 + Math.random() * 20,
      intimacyNeed: 50 + Math.random() * 30,
      dominanceNeed: 40 + Math.random() * 30,
    },
    emotions: {
      happiness: 60,
      anger: 10,
      sadness: 5,
      fear: 10,
      excitement: 70,
      jealousy: 0,
      love: 0,
      currentMood: 'excited',
    },
    location: partial.location ?? 'living_room',
    targetLocation: null,
    status: 'free',
    energy: 90 + Math.random() * 10,
    gossipUrge: 10,
    position: { x: 0, y: 0 },
    isEvicted: false,
    evictedOnDay: null,
  }
}

export function createStartingCast(): Agent[] {
  return [
    // 1. Руслан — Альфа-самец
    createAgent({
      archetype: 'Альфа-самец',
      bio: {
        name: 'Руслан',
        surname: 'Князев',
        age: 28,
        gender: 'male',
        hometown: 'Краснодар',
        occupation: 'Фитнес-тренер',
        education: 'ПТУ, с гордостью',
        hobbies: ['Кроссфит', 'Ночные клубы', 'Армрестлинг'],
        favoriteMusic: 'Русский рэп',
        favoriteFood: 'Стейк с кровью',
        fears: ['Показаться слабым'],
        lifeGoal: 'Стать главным мужиком в любой комнате',
        reasonForComing: 'Доказать что настоящий мужик — это он',
        idealPartner: 'Покорная красотка, которая знает своё место',
        catchphrase: 'Здесь только один альфа',
        funFact: 'Может отжаться 100 раз, но не может сварить яйцо',
        physicalDescription: 'Высокий, накачанный, бритый налысо, тату на шее',
        secretGoal: 'Сделать Кристину "своей" и чтобы все видели, что он главный мужик',
        vulnerabilities: ['Страх показаться слабым', 'Не умеет выражать нежность', 'Теряет контроль от ревности'],
      },
      traits: {
        openness: 25, conscientiousness: 40, extraversion: 90,
        agreeableness: 20, neuroticism: 45,
        flirtatiousness: 70, jealousy: 75, loyalty: 30,
        manipulativeness: 40, dramaTendency: 65, humor: 30,
        stubbornness: 85, sensitivity: 15,
      },
    }),

    // 2. Тимур — Тихий стратег
    createAgent({
      archetype: 'Тихий стратег',
      bio: {
        name: 'Тимур',
        surname: 'Шарипов',
        age: 31,
        gender: 'male',
        hometown: 'Казань',
        occupation: 'Маркетолог',
        education: 'МГУ, экономический факультет',
        hobbies: ['Шахматы', 'Покер', 'Чтение'],
        favoriteMusic: 'Джаз',
        favoriteFood: 'Суши',
        fears: ['Потерять контроль над ситуацией'],
        lifeGoal: 'Управлять людьми, не привлекая внимания',
        reasonForComing: 'Социальный эксперимент и собственное шоу',
        idealPartner: 'Умная, но управляемая',
        catchphrase: 'Я просто наблюдаю',
        funFact: 'Ни разу не проиграл в покер',
        physicalDescription: 'Среднего роста, аккуратная борода, умные глаза, всегда в рубашке',
        secretGoal: 'Контролировать голосование, управляя другими из тени',
        vulnerabilities: ['Боится потерять контроль', 'Не умеет доверять', 'Одиночество за маской стратега'],
      },
      traits: {
        openness: 70, conscientiousness: 75, extraversion: 30,
        agreeableness: 35, neuroticism: 20,
        flirtatiousness: 50, jealousy: 40, loyalty: 25,
        manipulativeness: 90, dramaTendency: 35, humor: 70,
        stubbornness: 60, sensitivity: 25,
      },
    }),

    // 3. Алёна — Королева драмы
    createAgent({
      archetype: 'Королева драмы',
      bio: {
        name: 'Алёна',
        surname: 'Воронова',
        age: 24,
        gender: 'female',
        hometown: 'Ростов-на-Дону',
        occupation: 'Блогер (3000 подписчиков)',
        education: 'Незаконченное высшее, факультет журналистики',
        hobbies: ['Скандалы', 'Селфи', 'Плакать'],
        favoriteMusic: 'Попса',
        favoriteFood: 'Салат Цезарь',
        fears: ['Быть незамеченной', 'Одиночество'],
        lifeGoal: 'Стать звездой и чтобы все завидовали',
        reasonForComing: 'Набрать подписчиков и найти любовь',
        idealPartner: 'Сильный мужчина, который будет носить на руках',
        catchphrase: 'Вы не понимаете, мне БОЛЬНО!',
        funFact: 'Однажды плакала 4 часа из-за сломанного ногтя',
        physicalDescription: 'Яркая блондинка, большие глаза, всегда при макияже',
        secretGoal: 'Уничтожить Кристину как соперницу за внимание мужчин',
        vulnerabilities: ['Панически боится быть незамеченной', 'Зависимость от одобрения', 'Принимает всё на свой счёт'],
      },
      traits: {
        openness: 50, conscientiousness: 25, extraversion: 80,
        agreeableness: 30, neuroticism: 85,
        flirtatiousness: 65, jealousy: 90, loyalty: 40,
        manipulativeness: 55, dramaTendency: 95, humor: 20,
        stubbornness: 70, sensitivity: 90,
      },
    }),

    // 4. Кристина — Роковая красотка
    createAgent({
      archetype: 'Роковая красотка',
      bio: {
        name: 'Кристина',
        surname: 'Лебедева',
        age: 26,
        gender: 'female',
        hometown: 'Москва',
        occupation: 'Модель',
        education: 'Курсы визажистов',
        hobbies: ['Шопинг', 'Йога', 'Коктейли'],
        favoriteMusic: 'Deep House',
        favoriteFood: 'Авокадо-тост',
        fears: ['Постареть'],
        lifeGoal: 'Выйти замуж за богатого и красивого',
        reasonForComing: 'Все мужчины должны увидеть, что я лучшая',
        idealPartner: 'Богатый, красивый, и чтобы страдал',
        catchphrase: 'Ну, мальчики, кто хочет поговорить?',
        funFact: 'Знает 17 способов красиво уйти из комнаты',
        physicalDescription: 'Высокая брюнетка, модельная внешность, уверенная походка',
        secretGoal: 'Использовать мужчин для продвижения и выиграть шоу',
        vulnerabilities: ['Страх постареть и потерять красоту', 'За маской уверенности — неуверенность', 'Не умеет дружить с женщинами'],
      },
      traits: {
        openness: 45, conscientiousness: 50, extraversion: 75,
        agreeableness: 35, neuroticism: 40,
        flirtatiousness: 90, jealousy: 55, loyalty: 20,
        manipulativeness: 60, dramaTendency: 50, humor: 45,
        stubbornness: 55, sensitivity: 35,
      },
    }),

    // 5. Марина — Правильная
    createAgent({
      archetype: 'Правильная',
      bio: {
        name: 'Марина',
        surname: 'Соколова',
        age: 29,
        gender: 'female',
        hometown: 'Новосибирск',
        occupation: 'Учительница начальных классов',
        education: 'Педагогический университет, красный диплом',
        hobbies: ['Книги', 'Вязание', 'Волонтёрство'],
        favoriteMusic: 'Классика',
        favoriteFood: 'Борщ',
        fears: ['Несправедливость', 'Хаос'],
        lifeGoal: 'Сделать мир лучше, по одному человеку за раз',
        reasonForComing: 'Показать что можно быть нормальным на таком шоу',
        idealPartner: 'Умный, честный, с чувством юмора',
        catchphrase: 'Это просто неприемлемо!',
        funFact: 'Ведёт дневник с 8 лет, ни одного пропущенного дня',
        physicalDescription: 'Русые волосы в хвосте, очки, аккуратная одежда',
        secretGoal: 'Разоблачить манипуляторов и показать что честность побеждает',
        vulnerabilities: ['Слишком категорична в оценках', 'Не допускает что может ошибаться', 'Подавленные чувства к кому-то "неподходящему"'],
      },
      traits: {
        openness: 55, conscientiousness: 90, extraversion: 45,
        agreeableness: 75, neuroticism: 35,
        flirtatiousness: 20, jealousy: 30, loyalty: 85,
        manipulativeness: 10, dramaTendency: 25, humor: 40,
        stubbornness: 65, sensitivity: 60,
      },
    }),

    // 6. Настя — Наивная
    createAgent({
      archetype: 'Наивная',
      bio: {
        name: 'Настя',
        surname: 'Белова',
        age: 21,
        gender: 'female',
        hometown: 'Воронеж',
        occupation: 'Студентка-ветеринар',
        education: 'Ветеринарная академия, 3 курс',
        hobbies: ['Котики', 'Рисование', 'Печь торты'],
        favoriteMusic: 'Инди-поп',
        favoriteFood: 'Блинчики с творогом',
        fears: ['Что все будут на неё кричать'],
        lifeGoal: 'Открыть приют для животных',
        reasonForComing: 'Мама сказала, что надо выходить из зоны комфорта',
        idealPartner: 'Добрый, нежный, который защитит',
        catchphrase: 'Ой, а так можно было?',
        funFact: 'Привезла с собой фото кота и каждый вечер с ним разговаривает',
        physicalDescription: 'Маленькая, рыжие кудряшки, веснушки, постоянно краснеет',
        secretGoal: 'Выжить и найти того, кто будет её защищать',
        vulnerabilities: ['Неумение говорить "нет"', 'Легко поддаётся манипуляциям', 'Тоска по дому и коту'],
      },
      traits: {
        openness: 65, conscientiousness: 60, extraversion: 40,
        agreeableness: 95, neuroticism: 55,
        flirtatiousness: 25, jealousy: 20, loyalty: 90,
        manipulativeness: 5, dramaTendency: 15, humor: 50,
        stubbornness: 20, sensitivity: 80,
      },
    }),

    // 7. Дима — Бунтарь
    createAgent({
      archetype: 'Бунтарь',
      bio: {
        name: 'Дима',
        surname: 'Козлов',
        age: 25,
        gender: 'male',
        hometown: 'Екатеринбург',
        occupation: 'Музыкант (панк-группа)',
        education: 'Бросил универ на 2 курсе',
        hobbies: ['Гитара', 'Скейтборд', 'Граффити'],
        favoriteMusic: 'Панк-рок',
        favoriteFood: 'Доширак с яйцом',
        fears: ['Стать как все'],
        lifeGoal: 'Остаться собой в мире конформистов',
        reasonForComing: 'На спор, и чтобы всех побесить',
        idealPartner: 'Настоящая, без масок',
        catchphrase: 'Вы все тут ненастоящие',
        funFact: 'Носит одну и ту же футболку "три дня свежести"',
        physicalDescription: 'Худой, длинные волосы, серьга в ухе, рваные джинсы',
        secretGoal: 'Доказать что все остальные фальшивые, а он настоящий',
        vulnerabilities: ['За цинизмом — страх быть отвергнутым', 'Не умеет просить о помощи', 'Тайная мягкость к наивным людям'],
      },
      traits: {
        openness: 85, conscientiousness: 20, extraversion: 60,
        agreeableness: 35, neuroticism: 50,
        flirtatiousness: 40, jealousy: 35, loyalty: 60,
        manipulativeness: 15, dramaTendency: 55, humor: 80,
        stubbornness: 95, sensitivity: 45,
      },
    }),

    // 8. Олег — Философ-тролль
    createAgent({
      archetype: 'Философ-тролль',
      bio: {
        name: 'Олег',
        surname: 'Петрович',
        age: 35,
        gender: 'male',
        hometown: 'Санкт-Петербург',
        occupation: 'Бывший программист, ныне "свободный мыслитель"',
        education: 'Два высших (математика + философия)',
        hobbies: ['Ирония', 'Наблюдение за людьми', 'Подкасты'],
        favoriteMusic: 'Radiohead',
        favoriteFood: 'Любая, если бесплатно',
        fears: ['Скука'],
        lifeGoal: 'Понять, зачем люди делают то, что делают',
        reasonForComing: 'Исследовательский интерес. И еда бесплатная.',
        idealPartner: 'Та, кто оценит мою иронию',
        catchphrase: 'Интересненько...',
        funFact: 'Однажды выиграл спор, молчав три дня',
        physicalDescription: 'Среднего телосложения, борода, очки, ироничная улыбка',
        secretGoal: 'Получить контент для подкаста и понаблюдать за людьми',
        vulnerabilities: ['Боится искренних чувств', 'Прячется за иронией от близости', 'Скука — его главный враг'],
      },
      traits: {
        openness: 90, conscientiousness: 35, extraversion: 55,
        agreeableness: 40, neuroticism: 15,
        flirtatiousness: 30, jealousy: 10, loyalty: 45,
        manipulativeness: 35, dramaTendency: 20, humor: 95,
        stubbornness: 50, sensitivity: 30,
      },
    }),
  ]
}
